import re

from src.utils import fs
from src.dependencies import path as path_utils


# Generates the XML contents of the Network Security File.
def generate_config(certificate_path=None):
    certificate_block = generate_certificate_block(certificate_path) if certificate_path else ''

    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '  <!-- Intentionally lax Network Security Configuration (generated by apk-mitm) -->\n'
        '  <network-security-config>\n'
        '    <!-- Allow cleartext traffic -->\n'
        '    <base-config cleartextTrafficPermitted="true">\n'
        '      <trust-anchors>\n'
        '        <!-- Allow user-added (proxy) certificates -->\n'
        '        <certificates src="user" />' + certificate_block + '\n'
        '        <certificates src="system" />\n'
        '      </trust-anchors>\n'
        '    </base-config>\n'
        '  </network-security-config>'
    )


# Generates the XML block responsible for registering a custom certificate.
def generate_certificate_block(path):
    file_name = path_utils.basename(path)

    # Android resources are always referred to without their file extension
    resource_name = re.sub(r'\.[a-z\d]+$', '', file_name)

    return (
        '\n\n'
        '        <!-- Allow specific certificate -->\n'
        '        <certificates src="@raw/' + resource_name + '" />\n'
    )


async def create_network_security_config(path, certificate_path=None):
    await fs.mkdir(path_utils.dirname(path), {'recursive': True})

    config = generate_config(certificate_path=certificate_path)
    await fs.write_file(path, config, 'utf-8')
